import {
  Device,
  LaptopTelemetry,
  MobileTelemetry,
  IoTTelemetry,
  Alert,
  AIAssessment,
  Recommendation,
  RiskLevel,
} from '../types';

export type DemoScenario = 'NORMAL' | 'MEDIUM' | 'HIGH';

export interface DemoDataSet {
  devices: Device[];
  laptop: LaptopTelemetry;
  mobile: MobileTelemetry;
  iot: IoTTelemetry;
  assessment: AIAssessment;
  recommendations: Recommendation[];
  alerts: Alert[];
}

export const DEMO_DATA_SETS: Record<DemoScenario, DemoDataSet> = {
  NORMAL: {
    devices: [
      {
        deviceId: 'demo-laptop',
        deviceName: 'ThinkPad X1 Carbon (Demo)',
        deviceType: 'laptop',
        connectionStatus: 'connected',
        lastUpdated: '2026-10-02T08:45:10Z',
        riskLevel: 'NORMAL',
        anomalyScore: 0,
      },
      {
        deviceId: 'demo-mobile',
        deviceName: 'Pixel 9 Pro (Demo)',
        deviceType: 'mobile',
        connectionStatus: 'connected',
        lastUpdated: '2026-10-02T08:45:10Z',
        riskLevel: 'NORMAL',
        anomalyScore: 0,
      },
      {
        deviceId: 'demo-iot',
        deviceName: 'ESP32 Sensor Unit (Demo)',
        deviceType: 'iot',
        connectionStatus: 'connected',
        lastUpdated: '2026-10-02T08:45:10Z',
        riskLevel: 'NORMAL',
        anomalyScore: 0,
      },
    ],
    laptop: {
      deviceId: 'demo-laptop',
      deviceType: 'laptop',
      timestamp: '2026-10-02T08:45:10Z',
      cpu: 24.5,
      ram: 46.2,
      disk: 58.0,
      uploadMb: 1.8,
      downloadMb: 9.4,
      processes: 198,
      anomalyScore: 0,
      risk: 'NORMAL',
      reason: 'No unusual behaviour detected.',
    },
    mobile: {
      deviceId: 'demo-mobile',
      deviceType: 'mobile',
      timestamp: '2026-10-02T08:45:10Z',
      storagePercent: 54.0,
      freeStorageGb: 118.5,
      batteryPercent: 88,
      temperature: 32.4,
      temperatureUnit: 'C',
      charging: false,
      networkStatus: 'wifi',
      dataUsageMb: 142.0,
      anomalyScore: 0,
      risk: 'NORMAL',
      reason: 'Normal mobile battery and temperature conditions.',
    },
    iot: {
      deviceId: 'demo-iot',
      deviceType: 'iot',
      timestamp: '2026-10-02T08:45:10Z',
      temperature: 23.5,
      humidity: 48.0,
      motion: false,
      voltage: 4.8,
      current: 0.12,
      anomalyScore: 0,
      risk: 'NORMAL',
      reason: 'ESP32 environment readings within nominal range.',
    },
    assessment: {
      deviceId: 'demo-laptop',
      risk: 'NORMAL',
      assessment: 'No unusual device behaviour detected. Current readings are within the configured monitoring thresholds.',
      recommendedActions: [
        'Maintain routine operating system updates.',
        'Keep standard monitoring enabled.',
      ],
      generatedAt: '2026-10-02T08:45:10Z',
    },
    recommendations: [
      {
        id: 'rec-demo-01',
        priority: 'LOW',
        title: 'All systems optimal',
        description: 'No remediations needed. All parameters are operating within safe security envelopes.',
        safe: true,
      },
    ],
    alerts: [],
  },

  MEDIUM: {
    devices: [
      {
        deviceId: 'demo-laptop',
        deviceName: 'ThinkPad X1 Carbon (Demo)',
        deviceType: 'laptop',
        connectionStatus: 'connected',
        lastUpdated: '2026-10-02T09:12:30Z',
        riskLevel: 'MEDIUM',
        anomalyScore: 2,
      },
      {
        deviceId: 'demo-mobile',
        deviceName: 'Pixel 9 Pro (Demo)',
        deviceType: 'mobile',
        connectionStatus: 'connected',
        lastUpdated: '2026-10-02T09:12:30Z',
        riskLevel: 'MEDIUM',
        anomalyScore: 1,
      },
      {
        deviceId: 'demo-iot',
        deviceName: 'ESP32 Sensor Unit (Demo)',
        deviceType: 'iot',
        connectionStatus: 'connected',
        lastUpdated: '2026-10-02T09:12:30Z',
        riskLevel: 'NORMAL',
        anomalyScore: 0,
      },
    ],
    laptop: {
      deviceId: 'demo-laptop',
      deviceType: 'laptop',
      timestamp: '2026-10-02T09:12:30Z',
      cpu: 84.2,
      ram: 88.5,
      disk: 78.0,
      uploadMb: 8.2,
      downloadMb: 112.5,
      processes: 380,
      anomalyScore: 2,
      risk: 'MEDIUM',
      reason: 'Elevated CPU utilization and persistent background network activity.',
    },
    mobile: {
      deviceId: 'demo-mobile',
      deviceType: 'mobile',
      timestamp: '2026-10-02T09:12:30Z',
      storagePercent: 88.4,
      freeStorageGb: 14.8,
      batteryPercent: 18,
      temperature: 39.1,
      temperatureUnit: 'C',
      charging: false,
      networkStatus: 'cellular',
      dataUsageMb: 840.0,
      anomalyScore: 1,
      risk: 'MEDIUM',
      reason: 'Mobile storage approaching capacity and low battery condition.',
    },
    iot: {
      deviceId: 'demo-iot',
      deviceType: 'iot',
      timestamp: '2026-10-02T09:12:30Z',
      temperature: 26.2,
      humidity: 54.0,
      motion: false,
      voltage: 4.6,
      current: 0.14,
      anomalyScore: 0,
      risk: 'NORMAL',
      reason: 'Normal sensor readings.',
    },
    assessment: {
      deviceId: 'demo-laptop',
      risk: 'MEDIUM',
      assessment: 'CPU usage is elevated and secondary download throughput has increased. Rule thresholds suggest reviewing running processes.',
      recommendedActions: [
        'Review active background applications and browser processes.',
        'Inspect ongoing network downloads.',
      ],
      generatedAt: '2026-10-02T09:12:30Z',
    },
    recommendations: [
      {
        id: 'rec-demo-02',
        priority: 'MEDIUM',
        title: 'Review heavy applications',
        description: 'Stop heavy background tasks or tabs causing sustained high CPU load.',
        safe: true,
      },
      {
        id: 'rec-demo-03',
        priority: 'MEDIUM',
        title: 'Connect mobile charger',
        description: 'Battery level is below 20%. Connect device to keep monitoring agent responsive.',
        safe: true,
      },
    ],
    alerts: [
      {
        alertId: 'demo-alt-01',
        deviceId: 'demo-laptop',
        deviceType: 'laptop',
        severity: 'MEDIUM',
        title: 'High CPU & Network Spike',
        message: 'CPU exceeded 80% for 5 consecutive minutes with elevated network usage.',
        timestamp: '10:42 AM',
        status: 'OPEN',
      },
      {
        alertId: 'demo-alt-02',
        deviceId: 'demo-mobile',
        deviceType: 'mobile',
        severity: 'MEDIUM',
        title: 'Storage Capacity Advisory',
        message: 'Internal storage reached 88% capacity. 14.8 GB remaining.',
        timestamp: '10:38 AM',
        status: 'OPEN',
      },
    ],
  },

  HIGH: {
    devices: [
      {
        deviceId: 'demo-laptop',
        deviceName: 'ThinkPad X1 Carbon (Demo)',
        deviceType: 'laptop',
        connectionStatus: 'connected',
        lastUpdated: '2026-10-02T09:30:15Z',
        riskLevel: 'HIGH',
        anomalyScore: 4,
      },
      {
        deviceId: 'demo-mobile',
        deviceName: 'Pixel 9 Pro (Demo)',
        deviceType: 'mobile',
        connectionStatus: 'connected',
        lastUpdated: '2026-10-02T09:30:15Z',
        riskLevel: 'HIGH',
        anomalyScore: 3,
      },
      {
        deviceId: 'demo-iot',
        deviceName: 'ESP32 Sensor Unit (Demo)',
        deviceType: 'iot',
        connectionStatus: 'connected',
        lastUpdated: '2026-10-02T09:30:15Z',
        riskLevel: 'MEDIUM',
        anomalyScore: 1,
      },
    ],
    laptop: {
      deviceId: 'demo-laptop',
      deviceType: 'laptop',
      timestamp: '2026-10-02T09:30:15Z',
      cpu: 96.8,
      ram: 94.2,
      disk: 96.1,
      uploadMb: 24.5,
      downloadMb: 285.0,
      processes: 520,
      anomalyScore: 4,
      risk: 'HIGH',
      reason: 'Critical CPU saturation (>95%), RAM exhaustion (>94%), and disk volume critical.',
    },
    mobile: {
      deviceId: 'demo-mobile',
      deviceType: 'mobile',
      timestamp: '2026-10-02T09:30:15Z',
      storagePercent: 97.2,
      freeStorageGb: 3.2,
      batteryPercent: 9,
      temperature: 44.5,
      temperatureUnit: 'C',
      charging: false,
      networkStatus: 'cellular',
      dataUsageMb: 1450.0,
      anomalyScore: 3,
      risk: 'HIGH',
      reason: 'Thermal threshold warning (44.5°C) and critical storage shortage.',
    },
    iot: {
      deviceId: 'demo-iot',
      deviceType: 'iot',
      timestamp: '2026-10-02T09:30:15Z',
      temperature: 38.0,
      humidity: 89.0,
      motion: true,
      voltage: 3.1,
      current: 0.45,
      anomalyScore: 1,
      risk: 'MEDIUM',
      reason: 'High ambient humidity and low supply voltage detected.',
    },
    assessment: {
      deviceId: 'demo-laptop',
      risk: 'HIGH',
      assessment: 'Multiple critical threshold limits breached across CPU, RAM, and Disk storage. Telemetry indicates severe system resource starvation.',
      recommendedActions: [
        'Close unneeded intensive processes and clean temporary volume storage.',
        'Verify running services to ensure no unauthorized compute workload.',
      ],
      generatedAt: '2026-10-02T09:30:15Z',
    },
    recommendations: [
      {
        id: 'rec-demo-04',
        priority: 'HIGH',
        title: 'Free storage by removing temporary files',
        description: 'Primary storage volume has under 4% remaining. Remove unnecessary downloads or purge cache.',
        safe: true,
      },
      {
        id: 'rec-demo-05',
        priority: 'HIGH',
        title: 'Allow mobile device to cool',
        description: 'Stop heavy applications and remove device case until temperature drops below 38°C.',
        safe: true,
      },
      {
        id: 'rec-demo-06',
        priority: 'HIGH',
        title: 'Connect mobile device to charger',
        description: 'Battery is below 10%. Connect power adapter to prevent system shutdown.',
        safe: true,
      },
    ],
    alerts: [
      {
        alertId: 'demo-alt-03',
        deviceId: 'demo-mobile',
        deviceType: 'mobile',
        severity: 'HIGH',
        title: 'Mobile Storage Critically Full',
        message: 'Storage usage has reached 97.2%. Only 3.2 GB available.',
        timestamp: '10:38 AM',
        status: 'OPEN',
      },
      {
        alertId: 'demo-alt-04',
        deviceId: 'demo-laptop',
        deviceType: 'laptop',
        severity: 'HIGH',
        title: 'Critical CPU & RAM Saturation',
        message: 'Workstation CPU at 96.8% and RAM at 94.2% with 520 active processes.',
        timestamp: '10:42 AM',
        status: 'OPEN',
      },
    ],
  },
};
